---
- name: Manage F5 Maintenance Mode without file storage
  hosts: localhost
  gather_facts: no

  vars:
    f5_host: "f5.example.com"
    f5_user: "admin"
    f5_password: "your_password"
    validate_certs: false
    partition: "Common"
    vs_name: "vs_web01"
    maintenance_irule_name: "maintenance_irule"
    maintenance_message: "<html><body><h1>Site Under Maintenance</h1><p>Please check back soon.</p></body></html>"
    maintenance_mode: "start"   # change to "end"
    prod_irules: []             # populate this only when restoring

  tasks:

    - name: Create or update maintenance iRule
      bigip_irule:
        server: "{{ f5_host }}"
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        validate_certs: "{{ validate_certs }}"
        partition: "{{ partition }}"
        name: "{{ maintenance_irule_name }}"
        content: |
          when HTTP_REQUEST {
              HTTP::respond 503 content {
                  {{ maintenance_message }}
              }
          }
        state: present
      when: maintenance_mode == "start"
      delegate_to: localhost

    - name: Get current iRules attached to VIP
      uri:
        url: "https://{{ f5_host }}/mgmt/tm/ltm/virtual/~{{ partition }}~{{ vs_name }}"
        method: GET
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        validate_certs: "{{ validate_certs }}"
        return_content: yes
      register: vs_config
      when: maintenance_mode == "start"
      delegate_to: localhost

    - name: Show current attached iRules for optional copy-paste
      debug:
        msg: "Current iRules on {{ vs_name }}: {{ vs_config.json.rules | default([]) }}"
      when: maintenance_mode == "start"

    - name: Apply maintenance iRule to VIP
      bigip_virtual_server:
        server: "{{ f5_host }}"
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ vs_name }}"
        partition: "{{ partition }}"
        rules:
          - "{{ maintenance_irule_name }}"
        state: present
      when: maintenance_mode == "start"
      delegate_to: localhost

    - name: Restore original iRules to VIP
      bigip_virtual_server:
        server: "{{ f5_host }}"
        user: "{{ f5_user }}"
        password: "{{ f5_password }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ vs_name }}"
        partition: "{{ partition }}"
        rules: "{{ prod_irules }}"
        state: present
      when: maintenance_mode == "end" and prod_irules | length > 0
      delegate_to: localhost