- name: Install rsyslog package SEC-4.1
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - rsyslog

- name: Check if rsyslog package are installed
  command: rpm -qa | grep -i "{{ item }}"
  loop:
    - rsyslog
  register: package_check
  
- name: enable rsyslog service
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - rsyslog

- name: Print package installation  results
  debug:
    msg: "rsyslog package is installed"
  when: package_check is succeeded
