FROM openjdk:8-jdk-alpine
MAINTAINER Ganesan Kandasamy <ganesan.kandasami@gmail.com>
MAINTAINER Ganesan Kandasamy <ganesan.kandasami@gmail.com>
ADD target/account-service.jar account-service.jar
EXPOSE 2222
ENTRYPOINT ["java", "-jar", "/account-service.jar"]